# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(698, 396)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(226, 226, 226);")
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 261, 421))
        self.frame.setStyleSheet("background-color: rgb(34, 34, 46);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(30, 10, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Britannic Bold")
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setStyleSheet("color: white\n"
"")
        self.label.setObjectName("label")
        self.input_username = QtWidgets.QLineEdit(self.frame)
        self.input_username.setGeometry(QtCore.QRect(40, 140, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.input_username.setFont(font)
        self.input_username.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(34, 34, 46);\n"
"border-radius: 10;\n"
"")
        self.input_username.setText("")
        self.input_username.setAlignment(QtCore.Qt.AlignCenter)
        self.input_username.setObjectName("input_username")
        self.input_password = QtWidgets.QLineEdit(self.frame)
        self.input_password.setGeometry(QtCore.QRect(40, 200, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.input_password.setFont(font)
        self.input_password.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(34, 34, 46);\n"
"border-radius: 10;\n"
"")
        self.input_password.setText("")
        self.input_password.setAlignment(QtCore.Qt.AlignCenter)
        self.input_password.setObjectName("input_password")
        self.input_port = QtWidgets.QLineEdit(self.frame)
        self.input_port.setGeometry(QtCore.QRect(40, 260, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.input_port.setFont(font)
        self.input_port.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(34, 34, 46);\n"
"border-radius: 10;\n"
"")
        self.input_port.setText("")
        self.input_port.setAlignment(QtCore.Qt.AlignCenter)
        self.input_port.setObjectName("input_port")
        self.input_host = QtWidgets.QLineEdit(self.frame)
        self.input_host.setGeometry(QtCore.QRect(40, 80, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.input_host.setFont(font)
        self.input_host.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(34, 34, 46);\n"
"border-radius: 10;\n"
"")
        self.input_host.setText("")
        self.input_host.setAlignment(QtCore.Qt.AlignCenter)
        self.input_host.setObjectName("input_host")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(40, 320, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(255, 62, 65);\n"
"    border-radius: 10;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(220, 51, 60);\n"
"    border-radius: 10;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(370, 10, 251, 51))
        font = QtGui.QFont()
        font.setFamily("Britannic Bold")
        font.setPointSize(24)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: #22222e\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(290, 90, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: #22222e\n"
"")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(290, 160, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: #22222e\n"
"")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(290, 230, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: #22222e\n"
"")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(290, 300, 241, 51))
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: #22222e\n"
"")
        self.label_6.setObjectName("label_6")
        self.output_type = QtWidgets.QListWidget(self.centralwidget)
        self.output_type.setGeometry(QtCore.QRect(370, 100, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(16)
        self.output_type.setFont(font)
        self.output_type.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(34, 34, 46);\n"
"border-radius: 10;\n"
"")
        self.output_type.setObjectName("output_type")
        self.output_version = QtWidgets.QListWidget(self.centralwidget)
        self.output_version.setGeometry(QtCore.QRect(410, 170, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(16)
        self.output_version.setFont(font)
        self.output_version.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(34, 34, 46);\n"
"border-radius: 10;\n"
"")
        self.output_version.setObjectName("output_version")
        self.output_kernel = QtWidgets.QListWidget(self.centralwidget)
        self.output_kernel.setGeometry(QtCore.QRect(410, 240, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.output_kernel.setFont(font)
        self.output_kernel.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(34, 34, 46);\n"
"border-radius: 10;\n"
"")
        self.output_kernel.setObjectName("output_kernel")
        self.output_cpu = QtWidgets.QListWidget(self.centralwidget)
        self.output_cpu.setGeometry(QtCore.QRect(550, 310, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(16)
        self.output_cpu.setFont(font)
        self.output_cpu.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(34, 34, 46);\n"
"border-radius: 10;\n"
"")
        self.output_cpu.setObjectName("output_cpu")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "SCAN PROFILE"))
        self.pushButton.setText(_translate("MainWindow", "SCAN"))
        self.label_2.setText(_translate("MainWindow", "RESULT OS SCAN"))
        self.label_3.setText(_translate("MainWindow", "TYPE:"))
        self.label_4.setText(_translate("MainWindow", "VERSION:"))
        self.label_5.setText(_translate("MainWindow", "KERNEL:"))
        self.label_6.setText(_translate("MainWindow", "CPU ARCHITECTURE:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
